### ISSUE TITLE
Error on test

### ISSUE THREAD

**Issue by tchedre** [LinusU/node-rrdtool#1]
**Error when testing open.js**

assert.js:85                                                                                                          
  throw new assert.AssertionError({                                                                                   
  ^                                                                                                                   
AssertionError: NaN == 95       

**Error when testing basic.js**

assert.js:85                                                                                                          
  throw new assert.AssertionError({                                                                                   
  ^                                                                                                                   
AssertionError: NaN == 98.9047

**Comment by LinusU** [comment]
Fixed by #3
